RFC: Burst support
litex-hub/wishbone-utils pull request #31
Opened 2020-10-24 04:32 UTC by bunnie

These are changes I've made so far to support burst-reads in wishbone tool. Conceivably burst-read() can be condensed into peek() by just using length=4 as a special case to go back to some fallback compatibility mode. For now, I've also got a program using the bridge directly to read data from a Precursor device currently doing RNG CI: https://github.com/betrusted-io/bt-rngd/blob/dc9522b22efd932362504ea5a9a3c594535de1e5/src/main.rs#L18

I think what would be great is if some review could be done to these and committed to a branch, which I can then use to base my next set of changes that will enable burst writing.

2020-10-24 06:16 UTC, mithro commented
@kgugala and I where just talking about this.
https://github.com/antmicro/litex-rowhammer-tester/issues/4

2020-10-24 09:02 UTC, xobs requested changes
Overall, a good approach.

I'll need to think of how to pass a reference to `&[u8]` to the USB thread, because that's the approach we'll want to take when we do the bridge. Maybe pass an `Arc` around. But at this point that's an implementation detail.

2020-10-26 18:21 UTC, bunnie commented on wishbone-tool/.cargo/config
> +linker = "arm-linux-gnueabihf-gcc-4.7"
No reason, I just didn't know what that is, and I don't have enough disk space to install the target. I'll revert that.

2020-10-26 18:25 UTC, bunnie commented
> The maxlen should be 65535. 1023 is the maximum amount of data in a single packet, and that's for isochronous.
> 
> This number indicates the amount of data in a transfer, and transfers are broken up into multiple packets. So you should be able to set this to 65535.

Just to document things, @xobs found this:

https://sourceforge.net/p/libusb/mailman/message/33339533/

Max length is 4096 due to an OS restriction, not a USB spec restriction.

2020-10-26 18:38 UTC, bunnie commented on wishbone-tool/crates/core/server/mod.rs
> +                            for i in 0..array.len() {
there is no emumerate() method on array

2020-10-26 18:39 UTC, bunnie commented on wishbone-tool/crates/bridge/src/lib.rs
> +    pub fn burst_read(&self, addr: u32, length: u32) -> Result<Vec<u8>, BridgeError> {
I tried doing this but then I got errors about "lifetimes" which I tried to clippy my way through but now I'm realizing I definitely do not understand enough Rust to deal with lifetimes. 

I guess what I have works, if you can refactor this and teach me how this should be done that would be great...

2020-10-26 18:41 UTC, bunnie commented
I've added burst write support, in addition to burst read support. I think I'll leave this branch here and continue on to the yak I really wanted to shave, which is USB-based programming of the ROM.

2020-10-27 12:03 UTC, merged